version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: rattrapage_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rattrapage_db
      MYSQL_USER: rattrapage_user
      MYSQL_PASSWORD: rattrapage_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/src/main/resources/db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - rattrapage_network

  server:
    build: ./server
    container_name: rattrapage_server
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rattrapage_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - rattrapage_network

  client:
    build: ./client
    container_name: rattrapage_client
    depends_on:
      - server
    ports:
      - "4200:80"
    networks:
      - rattrapage_network

volumes:
  mysql_data:

networks:
  rattrapage_network:
    driver: bridge
